source "https://rubygems.org"

gem "rails", "~> 8.0.2", ">= 8.0.2.1"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[windows jruby]

gem "rack-cors", "~> 3.0"

# Authentication stack
gem "devise", "~> 4.9"
gem "doorkeeper", "~> 5.7"
gem "doorkeeper-jwt"
gem "omniauth-google-oauth2", "~> 1.1"

# Utilities
gem "rspec-rails", "~> 8.0"

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false

  gem "bootsnap", require: false
end