name: Frontend CI (Vite + Vitest)

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/ci-frontend.yml"
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/ci-frontend.yml"
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Prettier
        run: npm run prettier:check --if-present

      - name: Test (Vitest + coverage)
        run: npm run test:coverage --if-present || npx vitest run --coverage --reporter=default
        env:
          CI: true

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: frontend/coverage
          if-no-files-found: ignore

      - name: Build (Vite)
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
          if-no-files-found: error